// <auto-generated />
using System;
using Aula04.RazorPages.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Aula04.RazorPages.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230909193456_AddAlunoAndCursoreal")]
    partial class AddAlunoAndCursoreal
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.4");

            modelBuilder.Entity("AlunoModelCursoModel", b =>
                {
                    b.Property<int>("AlunosAlunoID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CursosIdCurso")
                        .HasColumnType("INTEGER");

                    b.HasKey("AlunosAlunoID", "CursosIdCurso");

                    b.HasIndex("CursosIdCurso");

                    b.ToTable("AlunoModelCursoModel");
                });

            modelBuilder.Entity("Aula04.RazorPages.Models.AlunoModel", b =>
                {
                    b.Property<int?>("AlunoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DataInscricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeAluno")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AlunoID");

                    b.ToTable("Alunos");
                });

            modelBuilder.Entity("Aula04.RazorPages.Models.CursoModel", b =>
                {
                    b.Property<int?>("IdCurso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DataInicio")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataTérmino")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeCurso")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdCurso");

                    b.ToTable("Cursos");
                });

            modelBuilder.Entity("Aula04.RazorPages.Models.EventModel", b =>
                {
                    b.Property<int?>("EventID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("Date")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("EventID");

                    b.ToTable("Eventos", (string)null);
                });

            modelBuilder.Entity("Aula04.RazorPages.Models.PlayerModel", b =>
                {
                    b.Property<int?>("PlayerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("PlayerID");

                    b.ToTable("Jogadores", (string)null);
                });

            modelBuilder.Entity("EventoJogador", b =>
                {
                    b.Property<int>("EventID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayerID")
                        .HasColumnType("INTEGER");

                    b.HasKey("EventID", "PlayerID");

                    b.HasIndex("PlayerID");

                    b.ToTable("EventoJogador", (string)null);
                });

            modelBuilder.Entity("AlunoModelCursoModel", b =>
                {
                    b.HasOne("Aula04.RazorPages.Models.AlunoModel", null)
                        .WithMany()
                        .HasForeignKey("AlunosAlunoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Aula04.RazorPages.Models.CursoModel", null)
                        .WithMany()
                        .HasForeignKey("CursosIdCurso")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EventoJogador", b =>
                {
                    b.HasOne("Aula04.RazorPages.Models.EventModel", null)
                        .WithMany()
                        .HasForeignKey("EventID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Aula04.RazorPages.Models.PlayerModel", null)
                        .WithMany()
                        .HasForeignKey("PlayerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
